INSERT INTO VillagerPersonality (vp_type) VALUES ('Jock');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Bird');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ace',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Cranky');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Admiral',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Peppy');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Squirrel');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Agent S',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Uchi (Sisterly) ');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Pig');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Agnes',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Lazy');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Gorilla');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Al',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Alligator');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Alfonso',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Normal');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Koala');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Alice',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Snooty');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Alli',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Eagle');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Amelia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Anteater');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Anabelle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Anchovy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Bull');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Angus',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Mouse');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Anicotti',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Cat');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ankha',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Annalisa',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Horse');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Annalise',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Antonio',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Apollo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Hamster');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Apple',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Kangaroo');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Astrid',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Peppy');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Wolf');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Audie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Penguin');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Aurora',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Chicken');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ava',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Avery',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Elephant');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Axel',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Rhino');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Azalea',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Sheep');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Baabara',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Deer');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bam',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Tiger');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bangle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Cub');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Barold',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Dog');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bea',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Smug');
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Bear');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Beardo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Beau',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Becky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bella',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Benedict',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Benjamin',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Hippo');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bertha',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bettina',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bianca',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Biff',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Big Top',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Duck');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bill',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Goat');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Billy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Biskit',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bitty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Blaire',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Ostrich');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Blanche',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bluebear',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bob',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Rabbit');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bonbon',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bones',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Boomer',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Boone',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Boots',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Boris',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Boyd',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bree',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Broccolo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Broffina',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bruce',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bubbles',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Buck',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Lion');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bud',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Bunnie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Butch',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Buzz',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cally',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Frog');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Camofrog',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Canberra',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Candi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Carmen',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Caroline',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Carrie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cashmere',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Celia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Octopus');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cephalobot',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Octopus'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cesar',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chabwick',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chadder',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chai',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Charlise',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chelsea',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cheri',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cherry',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chester',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chevre',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chief',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chops',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chow',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Chrissy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Claude',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Claudia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Clay',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cleo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Clyde',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Coach',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cobb',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Coco',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cole',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Colton',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cookie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cousteau',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cranston',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Croque',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cube',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Curlos',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Curly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Curt',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Cranky');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cyd',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Cyrano',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Daisy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Deena',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Deirdre',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Del',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Monkey');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Deli',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Derwin',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Diana',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Diva',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Dizzy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Dobie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Doc',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Jock');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Dom',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Dora',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Dotty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Drago',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Drake',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Drift',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ed',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Egbert',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Elise',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ellie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Elmer',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Eloise',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Elvis',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Erik',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Étoile',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Eugene',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Eunice',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Faith',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Fang',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Fauna',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Felicity',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Filbert',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Flip',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Flo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Flora',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Flurry',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Francine',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Frank',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Freckles',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Frett',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Freya',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Friga',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Frita',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Frobert',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Fuchsia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gabi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gala',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gaston',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gayle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Genji',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gigi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gladys',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gloria',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Goldie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gonzo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Goose',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Graham',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Greta',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Grizzly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Groucho',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gruff',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Gwen',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hamlet',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hamphrey',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hans',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Harry',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hazel',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Henry',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hippeux',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hopkins',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hopper',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hornsby',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Huck',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Hugh',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Iggly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ike',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ione',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jacob',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jacques',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jambette',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jay',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jeremiah',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Jitters',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Joey',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Snooty');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Judy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Julia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Julian',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('June',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kabuki',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Katt',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Keaton',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ken',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ketchup',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kevin',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kid Cat',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kidd',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kiki',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kitt',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kitty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Klaus',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Knox',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kody',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Kyle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Leonardo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Leopold',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lily',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Limberg',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lionel',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lobo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lolly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lopez',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Louie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lucha',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lucky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lucy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Lyman',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mac',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Maddie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Maelle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Maggie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mallary',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Maple',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marcel',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marcie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Margie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marina',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Octopus'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marlo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marshal',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Marty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mathilda',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Megan',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Melba',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Merengue',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Merry',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Midge',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mint',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mira',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Miranda',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mitzi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Moe',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Molly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Monique',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Monty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Moose',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Mott',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Muffy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Murphy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Nan',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Nana',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO VillagerSpecies (vs_spec) VALUES ('Cow');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Naomi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cow'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Nate',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Nibbles',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Norma',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cow'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Octavian',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Octopus'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('O'Hare',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Olaf',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Olive',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Olivia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Opal',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ozzie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pancetti',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pango',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Paolo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Papi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pashmina',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pate',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Patty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cow'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Paula',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Peaches',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Peanut',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pecan',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Peck',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Peewee',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Peggy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pekoe',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Penelope',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Petri',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Phil',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Phoebe',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pierce',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pietro',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pinky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Piper',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pippy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Plucky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Chicken'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pompom',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Poncho',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Poppy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Portia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Prince',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Puck',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Puddles',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Pudge',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Punchy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Purrl',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Queenie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Quillson',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Quinn',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Raddle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rasher',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Smug');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Raymond',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Renée',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO VillagerPersonality (vp_type) VALUES ('Uchi (Sisterly)');
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Reneigh',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly)'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rex',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rhonda',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ribbot',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ricky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rilla',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rio',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rizzo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Roald',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Robin',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rocco',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hippo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rocket',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rod',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rodeo',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rodney',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rolf',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rooney',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rory',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Lion'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Roscoe',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rosie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Roswell',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rowan',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ruby',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Rudy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sally',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Samson',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Mouse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sandy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sasha',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Savannah',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Scoot',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Shari',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sheldon',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Shep',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sherb',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Shino',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Simon',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Skye',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sly',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Alligator'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Snake',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Snooty',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Soleil',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Hamster'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sparro',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Spike',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Spork',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sprinkle',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sprocket',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Ostrich'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Static',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Stella',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sterling',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Eagle'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Stinky',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Stitches',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Stu',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sydney',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sylvana',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Sylvia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('T-Bone',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tabby',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tad',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tammi',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tammy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tangy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tank',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rhino'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tasha',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Squirrel'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Teddy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tex',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tia',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tiansheng',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Monkey'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tiffany',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Timbra',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tipper',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cow'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Toby',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Rabbit'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tom',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Truffles',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Pig'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tucker',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Elephant'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tutu',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Twiggy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bird'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Tybalt',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Tiger'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Jock'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Ursala',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bear'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Uchi (Sisterly) '))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Velma',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Goat'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Vesta',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Vic',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Bull'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Victoria',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Violet',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Gorilla'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Vivian',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Vladimir',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Cub'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Wade',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Penguin'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Walker',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Dog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Walt',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Kangaroo'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Wart Jr.',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Frog'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Weber',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Duck'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Wendy',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Whitney',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Willow',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Sheep'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Winnie',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Horse'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Peppy'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Wolfgang',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Wolf'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Cranky'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Yuka',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Koala'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Snooty'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Zell',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Deer'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Smug'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Zoe',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Anteater'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Normal'))
INSERT INTO Villager (v_name,vs_id,vp_id) VALUES ('Zucker',(SELECT vs_id FROM VillagerSpecies WHERE vs_spec = 'Octopus'),(SELECT vp_id FROM VillagerPersonality WHERE vp_type = 'Lazy'))
